# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: git@github.com:famedly/backend-pre-commit-templates.git
    rev: 5414ae52c3eff663ee2e79b4abae1761172bdbc4
    hooks:
      - id: fmt
      - id: clippy
  - repo: https://github.com/crate-ci/typos
    rev: dictgen-v0.3.1
    hooks:
      - id: typos
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        files: ^README.md$
        args:
          - --github
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
  - repo: https://github.com/zimbatm/mdsh.git
    rev: v0.9.2
    hooks:
      - id: mdsh
