[package]
name = "zitadel-actions-manager"
version = "0.3.1"
edition = "2021"
default-run = "zitadel-actions-sync"

[dependencies]
as_variant = "1.2.0"
famedly_rust_utils = "0.2.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.11"
tracing = "0.1.41"
tracing-error = "0.2.1"
trait-variant = "0.1.2"
url = "2.5.4"

# For the CLI tool:
clap = { version = "4.5.24", features = [
    "derive",
    "string",
    "env",
], optional = true }
jsonwebtoken = { version = "9.3.0", optional = true }
reqwest = { version = "0.12.12", features = ["json"], optional = true }
serde_json = { version = "1.0.135", optional = true }
time = { version = "0.3.37", optional = true }
tokio = { version = "1.44.2", features = [
    "macros",
    "rt",
    "rt-multi-thread",
], optional = true }
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
], optional = true }

# For zitadel-rust-client:
anyhow = { version = "1.0.95", optional = true }
futures = { version = "0.3.31", optional = true }
zitadel-rust-client = { git = "https://github.com/famedly/zitadel-rust-client.git", tag = "v0.7.0", optional = true, default-features = false }

[features]
cli = ["clap", "simple-client", "tokio", "tracing-subscriber"]
simple-client = [
    "famedly_rust_utils/reqwest",
    "jsonwebtoken",
    "reqwest",
    "serde_json",
    "time",
]
zitadel-rust-client = ["anyhow", "dep:zitadel-rust-client", "futures"]

[[bin]]
name = "zitadel-actions-sync"
path = "src/main.rs"
required-features = ["cli"]

[dev-dependencies]
serde_json = "1.0.135"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }
url-macro = "0.2.0"
tokio = { version = "1.44.2", features = ["macros", "rt", "rt-multi-thread"] }

[build-dependencies]
vergen = { version = "8.2.6", features = [
    "git",
    "gitcl",
    "build",
] } # vergen passes metadata like the version and git commit hash to cargo as a compile-time environment variables

[lints.rust]
dead_code = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

[lints.clippy]
tabs_in_doc_comments = "allow"
branches_sharing_code = "warn"
cast_lossless = "warn"
cast_possible_wrap = "warn"
checked_conversions = "warn"
cloned_instead_of_copied = "warn"
create_dir = "warn"
dbg_macro = "warn"
default_trait_access = "warn"
expect_used = "warn"
# We already warn for `.expect`, except in tests, so this lint only
# hits tests where we don't care about it
expect_fun_call = "allow"
expl_impl_clone_on_copy = "warn"
fallible_impl_from = "warn"
filetype_is_file = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
float_cmp = "warn"
fn_params_excessive_bools = "warn"
fn_to_numeric_cast_any = "warn"
future_not_send = "warn"
if_then_some_else_none = "warn"
implicit_clone = "warn"
implicit_hasher = "warn"
implicit_saturating_sub = "warn"
imprecise_flops = "warn"
inefficient_to_string = "warn"
items_after_statements = "warn"
iter_not_returning_iterator = "warn"
large_digit_groups = "warn"
large_stack_arrays = "warn"
large_types_passed_by_value = "warn"
lossy_float_literal = "warn"
macro_use_imports = "warn"
manual_let_else = "warn"
manual_ok_or = "warn"
many_single_char_names = "warn"
map_unwrap_or = "warn"
mem_forget = "warn"
#missing_const_for_fn = "warn"
missing_docs_in_private_items = "warn"
must_use_candidate = "warn"
mut_mut = "warn"
mutex_atomic = "warn"
needless_bitwise_bool = "warn"
non_send_fields_in_send_ty = "warn"
option_option = "warn"
path_buf_push_overwrite = "warn"
print_stderr = "warn"
print_stdout = "warn"
ptr_as_ptr = "warn"
range_minus_one = "warn"
range_plus_one = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_closure_for_method_calls = "warn"
ref_binding_to_reference = "warn"
ref_option_ref = "warn"
return_self_not_must_use = "warn"
same_functions_in_if_condition = "warn"
same_name_method = "warn"
semicolon_if_nothing_returned = "warn"
str_to_string = "warn"
string_to_string = "warn"
suboptimal_flops = "warn"
suspicious_operation_groupings = "warn"
too_many_lines = "warn"
trait_duplication_in_bounds = "warn"
trivially_copy_pass_by_ref = "warn"
type_repetition_in_bounds = "warn"
undocumented_unsafe_blocks = "warn"
unnested_or_patterns = "warn"
unreadable_literal = "warn"
unseparated_literal_suffix = "warn"
unused_async = "warn"
unused_self = "warn"
unwrap_used = "warn"
used_underscore_binding = "warn"
useless_let_if_seq = "warn"
verbose_file_reads = "warn"
