# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

name: "Docker"

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  build:
    uses: famedly/backend-build-workflows/.github/workflows/docker-backend.yml@fcc2ec82a725d5c4c9c6a8f19e8df101c178dcb6
    secrets: inherit
    with:
      targets: zitadel-actions-manager
