# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

name: "Docker"

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build:
    uses: famedly/backend-build-workflows/.github/workflows/docker-backend.yml@main
    secrets: inherit
    with:
      name: zitadel-actions-manager
